'use client';
import { useState } from 'react';
import api from '@/lib/api';

interface Question {
  question: string;
  options: string[];
  correct_answer: string;
  explanation: string;
}

interface AIQuizProps {
  lessonId: number;
  lessonContent: string;
}

export default function AIQuiz({ lessonId, lessonContent }: AIQuizProps) {
  const [questions, setQuestions] = useState<Question[]>([]);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [score, setScore] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generateQuiz = async () => {
    setLoading(true);
    setError(null);
    try {
      const { data } = await api.post('/ai/generate-quiz', {
        lessonId,
        content: lessonContent
      });
      setQuestions(data.questions);
    } catch (err: unknown) {
      const message = (err as { response?: { data?: { error?: string } } })?.response?.data?.error || 'Failed to generate quiz. Please try again.';
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async () => {
    if (Object.keys(answers).length < questions.length) {
      alert('Please answer all questions before submitting.');
      return;
    }

    try {
      const { data } = await api.post('/ai/submit-quiz', {
        quizId: lessonId,  // reuse lessonId — backend looks up quiz by lesson
        answers
      });
      setScore(data.score);
      setSubmitted(true);
    } catch {
      // Calculate score client-side as fallback
      let correct = 0;
      questions.forEach((q, i) => { if (answers[i] === q.correct_answer) correct++; });
      setScore(correct);
      setSubmitted(true);
    }
  };

  const retakeQuiz = () => {
    setAnswers({});
    setSubmitted(false);
    setScore(null);
  };

  // ── INITIAL STATE: show generate button ─────────────────────────
  if (questions.length === 0) {
    return (
      <div className="text-center p-8 bg-gradient-to-br from-purple-50 to-blue-50 rounded-2xl">
        <div className="text-5xl mb-4">🤖</div>
        <h3 className="text-xl font-bold mb-2">AI-Powered Quiz</h3>
        <p className="text-gray-500 mb-6">{"Generate a personalized quiz from this lesson's content"}</p>
        {error && <p className="text-red-500 text-sm mb-4">{error}</p>}
        <button
          onClick={generateQuiz}
          disabled={loading}
          className="bg-purple-600 text-white px-8 py-3 rounded-xl font-semibold hover:bg-purple-700 disabled:opacity-50 transition-all"
        >
          {loading ? (
            <span className="flex items-center gap-2">
              <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
              </svg>
              Generating Quiz...
            </span>
          ) : '✨ Generate Quiz'}
        </button>
        <p className="text-xs text-gray-400 mt-3">Takes 3–5 seconds · 10 questions generated by AI</p>
      </div>
    );
  }

  // ── RESULT STATE: show score ─────────────────────────────────────
  if (submitted && score !== null) {
    const pct = Math.round((score / questions.length) * 100);
    const grade = pct >= 80 ? { emoji: '🎉', msg: 'Excellent work!', color: 'text-green-600' }
      : pct >= 60 ? { emoji: '👍', msg: 'Good effort! Review the wrong answers.', color: 'text-yellow-600' }
      : { emoji: '📚', msg: 'Keep practicing — you\'ll get there!', color: 'text-red-500' };

    return (
      <div className="space-y-6">
        <div className="bg-white rounded-2xl shadow-lg p-8 text-center">
          <div className="text-6xl mb-4">{grade.emoji}</div>
          <p className="text-5xl font-bold mb-1">{pct}%</p>
          <p className="text-gray-500 mb-2">{score} out of {questions.length} correct</p>
          <p className={`font-medium ${grade.color}`}>{grade.msg}</p>
          <button onClick={retakeQuiz} className="mt-6 bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700">
            Retake Quiz
          </button>
        </div>

        {/* Show all questions with correct/wrong highlighting */}
        {questions.map((q, i) => {
          const isCorrect = answers[i] === q.correct_answer;
          return (
            <div key={i} className={`bg-white p-5 rounded-xl shadow border-l-4 ${isCorrect ? 'border-green-500' : 'border-red-400'}`}>
              <p className="font-medium mb-3">{i + 1}. {q.question}</p>
              <div className="space-y-2">
                {q.options.map(option => (
                  <div key={option} className={`p-3 rounded-lg text-sm ${
                    option === q.correct_answer ? 'bg-green-50 text-green-800 font-medium'
                    : option === answers[i] ? 'bg-red-50 text-red-700'
                    : 'bg-gray-50 text-gray-600'
                  }`}>
                    {option === q.correct_answer && '✓ '}
                    {option === answers[i] && option !== q.correct_answer && '✗ '}
                    {option}
                  </div>
                ))}
              </div>
              {!isCorrect && (
                <p className="mt-3 text-sm text-gray-600 bg-blue-50 p-3 rounded-lg">
                  💡 {q.explanation}
                </p>
              )}
            </div>
          );
        })}
      </div>
    );
  }

  // ── QUIZ-TAKING STATE: show questions with selectable options ────
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h3 className="text-xl font-bold">📝 Quiz</h3>
        <span className="text-sm text-gray-500">
          {Object.keys(answers).length} / {questions.length} answered
        </span>
      </div>

      {questions.map((q, i) => (
        <div key={i} className="bg-white p-5 rounded-xl shadow">
          <p className="font-medium mb-3">{i + 1}. {q.question}</p>
          <div className="space-y-2">
            {q.options.map(option => (
              <button
                key={option}
                onClick={() => setAnswers(prev => ({ ...prev, [i]: option }))}
                className={`w-full text-left p-3 rounded-lg text-sm transition-colors ${
                  answers[i] === option
                    ? 'bg-blue-100 text-blue-800 font-medium border-2 border-blue-500'
                    : 'bg-gray-50 text-gray-600 hover:bg-gray-100 border-2 border-transparent'
                }`}
              >
                {option}
              </button>
            ))}
          </div>
        </div>
      ))}

      <button
        onClick={handleSubmit}
        className="w-full bg-purple-600 text-white py-3 rounded-xl font-semibold hover:bg-purple-700 transition-colors"
      >
        Submit Quiz
      </button>
    </div>
  );
}
